name: Publish packages to NPM

on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          TAG=${GITHUB_REF:10}
          echo "TAG=$TAG"
          MODULE=`echo "$TAG" | sed -e 's/@rramk\/\([a-zA-Z].*\)@.*$/\1/'`
          cd ${GITHUB_WORKSPACE}/packages/${MODULE}
          pwd
          ls
          npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
