name: Push documentation to pages repo

env:
  GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}

on:
  # Trigger the workflow on push to main
  push:
    branches:
      - main

jobs:
  docspush:
    name: Push documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sdk monorepo
        uses: actions/checkout@v2
        with:
          path: monorepo

      - name: debug path
        run: |
          ls -al ${GITHUB_WORKSPACE}/monorepo/.github/scripts

      - name: Checkout docs repo
        uses: actions/checkout@v2
        with:
          path: docs

      - name: install node/npm
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: publish docs
        run: echo ${{ env.GITHUB_WORKSPACE }}
        run: bash ${{ env.GITHUB_WORKSPACE }}/monorepo/.github/scripts/pushdocs.sh


