name: Push documentation to pages repo

env:
  GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}

# Trigger the workflow on push to main or when a github release is created
on:
  push:
    branches:
      - main
    tags:
      - '*'
  release:
    types: [created]

jobs:
  docspush:
    name: Push documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sdk monorepo
        uses: actions/checkout@v2
        with:
          path: monorepo

      - name: Checkout github docs repo
        uses: actions/checkout@v2
        with:
          repository: rramk/rramtravisghtest
          path: docs

      - name: Install npm
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Push docs
        run: ${{ github.workspace }}/monorepo/.github/scripts/pushdocs.sh
        shell: bash


