name: Push documentation to pages repo

env:
  GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}

on:
  # Trigger the workflow on push to main
  push:
    branches:
      - main

jobs:
  docspush:
    name: Push documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sdk monorepo
        uses: actions/checkout@v2
        with:
          path: monorepo

      - name: Checkout github docs repo
        uses: actions/checkout@v2
        with:
          repository: rramk/rramtravisghtest
          # full clone needed in order to push
          # fetch-depth: 0
          path: docs

      - name: Install npm
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: publish docs
        run: ${{ github.workspace }}/monorepo/.github/scripts/pushdocs.sh
        shell: bash


